config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#all_accounts'
  get 'deposit' => 'accounts#deposit'
  get 'withdrawal' => 'accounts#withdrawal'
  post 'update_balance' => 'accounts#update_balance'
  get 'transfer' => 'accounts#transfer'
  post 'complete_transfer' => 'accounts#complete_transfer'

  resources :accounts
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def all_accounts
  	if current_user.role == 'admin'
  		@accounts = Account.all
  	else 
  		@accounts = Account.where(user_id: current_user.id)
  	end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/all_accounts.html.erb
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>

<% if current_user.role == 'client' %>
  <h1>Welcome to Bank And Trust, <%= current_user.first_name %></h1>
<% else %>
  <h1>Welcome Admin</h1>
<% end %>


<% if current_user.role == 'admin' %>
  <p>Here's a list of current accounts:</p>

  <table class="table">
    <thead>
      <tr>
      	<th>Account Type</th>
      		<% if current_user.role == 'admin' %>
  	    		<th>First Name</th>
  	    		<th>Last Name</th>
      		<% end %>
        <th>Account Number</th>
        <th>Balance</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @accounts.each do |account| %>
        <tr>
        	<td><%= account.account_type.capitalize %></td>
        		<% if current_user.role == 'admin' %>
  	      		<td><%= account.user.first_name %></td>
  	      		<td><%= account.user.last_name %></td>
        		<% end %>
          <td><%= account.id %></td>
          <td><%= number_to_currency account.balance %></td>
          <td><%= link_to 'Show', account %></td>
          <td><%= link_to 'Make A Deposit', deposit_path(id: account.id), class: 'btn btn-info' %></td>
          <td><%= link_to 'Make A Withdrawal', withdrawal_path(id: account.id), class: 'btn btn-warning' %></td>
          <% if current_user.role == 'admin' %>
            <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

<% else %>

  <div class="row">
    <% @accounts.each do |account| %>
      <div class="col-lg-6">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3><%= account.account_type %></h3>
            <p>Account Number: <%= account.id %></p>
          </div>
          <div class="panel-body">
            <center><div class="money_circle">
              <p><%= number_to_currency account.balance %></p>
            </div></center><br />
            <center><p><%= link_to 'Make A Deposit', deposit_path(id: account.id), class: 'btn btn-default' %> | <%= link_to 'Make A Withdrawal', withdrawal_path(id: account.id), class: 'btn btn-default' %></p></center><br /> 
            <center><p><%= link_to 'More Details', account, class: 'btn btn-default' %></p></center>
          </div>
        </div>
      </div>
    <%end %>
  </div>


<div>
	<p><%= link_to 'Open a New Account', new_account_path, class: 'btn btn-success' %></p>
</div>

<% end %>