config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#all_accounts'
  get 'deposit' => 'accounts#deposit'
  get 'withdrawal' => 'accounts#withdrawal'
  post 'update_balance' => 'accounts#update_balance'
  get 'transfer' => 'accounts#transfer'
  post 'complete_transfer' => 'accounts#complete_transfer'

  resources :accounts
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord

	include ChangeHistory

	belongs_to :user

	validates :balance, numericality: {greater_than: 0}
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    authorize! :destroy, @account
    @users = User.all
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @histories = History.where(object_name: "Account", object_id: @account.id)
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
    authorize! :update, @account
  end

  def deposit
    authorize! :update, @current_account 
    @current_account = Account.find(params[:id])
  end

  def withdrawal
    authorize! :update, @current_account
    @current_account = Account.find(params[:id])
  end

  def update_balance
    overdraft = false
    @account = Account.find(params[:id])
    current_balance = @account.balance
    if params[:transaction] == "deposit"
      @account.update(balance: current_balance + params[:balance].to_f)
    else
        if params[:balance].to_f > current_balance
          overdraft = true
        else
          @account.update(balance: current_balance - params[:balance].to_f)
        end
    end

    if overdraft == true
      redirect_to root_path, notice: "Withdrawal amount of $#{'%.2f' % params[:balance].to_f} exceeds your current balance of $#{current_balance}. Please enter a different amount."
    else
      AccountMailer.update_email(current_user, @account, params[:transaction], params[:balance], current_balance).deliver_now
      redirect_to root_path, notice: "Your #{params[:transaction]} of $#{'%.2f' % params[:balance]} has been made to account #{@account.id}."
    end
  end

  def transfer
    @from_account = Account.find(params[:id]) 
    @accounts = Account.where(user_id: current_user.id)
  end

  def complete_transfer
    @from_account = Account.find_by(user_id: current_user.id, id: params[:account_from])
    @to_account = Account.find_by(user_id: current_user.id, id: params[:account_to])

    from_current_balance = @from_account.balance
    to_current_balance = @to_account.balance
    overdraft = false
    same_account = false
    below_zero = false

    if params[:balance].to_f > from_current_balance
      overdraft = true

    elsif  params[:balance].to_f == from_current_balance 
        below_zero = true
    else
      if @from_account.id == @to_account.id
        same_account = true
      else
      @from_account.update(balance: from_current_balance - params[:balance].to_f)
      @to_account.update(balance: to_current_balance + params[:balance].to_f)
      end
    end

    if same_account == true
      redirect_to root_path, notice: "The transfer can not be the same as the transfer to account. Please select a different account to process the transaction."
    elsif overdraft == true 
      redirect_to root_path, notice: "Transfer amount of $#{'%.2f' % params[:balance].to_f} exceeds your current balance of $#{from_current_balance}. Please select a different amount."
    elsif below_zero == true
      redirect_to root_path, notice: "There must be a minimum of $0.01 in your account at all times. Please select another amount to transfer."
    else
      redirect_to root_path, notice: "Your transfer of $#{'%.2f' % params[:balance].to_f} from account# #{@from_account.id} to account# #{@to_account.id} has been made."
    end
  end

  # POST /accounts
  # POST /accounts.json
  def create
    authorize! :create, @account
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        # mailer for welcome email
        AccountMailer.welcome_email(current_user, @account).deliver_now

        format.html { redirect_to root_path, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    authorize! :destroy, @account
    @account.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:user_id, :balance, :account_type)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="field">
    <%= form.label :balance %>
    <%= form.text_field :balance, id: :account_balance %>
  </div>

  <div class="field">
    <%= form.label :account_type %>
    <%= form.select :account_type, ["Checking", "Savings"], id: :account_account_type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/deposit.html.erb
<h2>Please enter the amount you'd like to deposit:</h2>
<p>Current Balance: <%= number_to_currency @current_account.balance %> </p>



<%= form_tag update_balance_path do %>
      <%= number_field_tag :balance, 0.01, min: 0.01, step: :any %>
      <%= hidden_field_tag :id, @current_account.id %>
      <%= hidden_field_tag :user_id, current_user.id %>
      <%= hidden_field_tag :transaction, "deposit" %>
      <%= submit_tag "Update Balance", class: "btn btn-success" %>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', root_path, class: 'btn btn-info' %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<table class="table">
  <thead>
    <tr>
      <th>Email</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', root_path, class: 'btn btn-info' %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<% if current_user.role == 'admin' %>
	<p>
		<strong>First Name</strong>
		<%= @account.user.first_name %>
	</p>

	<p>
		<strong>Last Name</strong>
		<%= @account.user.last_name %>
	</p>
<% end%>

<p>
  <strong>Account Number:</strong>
  <%= @account.id %>
</p>

<p>
  <strong>Balance:</strong>
  <%= number_to_currency @account.balance %>
</p>

<p>
  <strong>Account type:</strong>
  <%= @account.account_type.capitalize %>
</p>

<% if current_user.role == 'client' %>
	<%= link_to 'Make A Deposit', deposit_path(id: @account.id), class: 'btn btn-info' %> | <%= link_to 'Make A Withdrawal', withdrawal_path(id: @account.id), class: 'btn btn-danger' %> | <%= link_to 'Transfer Funds', transfer_path(id: @account.id), class: 'btn btn-warning' %>
<% end %>

<h3>Transaction History:</h3>

<table class="table">
  <thead>
    <tr>
    	<th>Date</th>
      <th>Time</th>
	    <th>Transaction Type</th>
	    <th>Amount</th>
      <th>Previous Balance</th>
      <th>Available Balance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @histories.each do |history| %>
      <tr>
      	<td><%= history.created_at.strftime("%B %d, %Y") %></td>
        <td><%= history.created_at.strftime("%I:%M:%P") %></td>
      	<% if history.before_value.to_f > history.after_value.to_f %>
      		<td>Withdrawal</td>
      	<% else %>
      		<td>Deposit</td>
      	<% end %>
	      <td><%= number_to_currency "#{(history.before_value.to_f - history.after_value.to_f).abs}" %></td>
	      <td><%= number_to_currency history.before_value.to_f %></td>
        <td><%= number_to_currency history.after_value.to_f %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back to Dashboard', root_path, class: 'btn btn-warning' %>

app/views/accounts/transfer.html.erb
<h2>Please enter the amount you'd like to transfer from Account Number <%= @from_account.id %>:</h2>

<p>Current Balance: <%= @from_account.balance %></p>

<%= form_tag complete_transfer_path do %>

	<%= hidden_field_tag :user_id, current_user.id %>
	<%= hidden_field_tag :account_from, @from_account.id %>
	<%= select_tag :account_to, options_for_select(current_user.accounts.collect{|a| [a.id, a.id]}) %>
  
  <%= number_field_tag :balance, 0.01, min: 0.01, step: :any %>
  <%= submit_tag "Complete Transfer", class: "btn btn-success" %>
<% end %>

app/views/accounts/withdrawal.html.erb
<h2>Please enter the amount you'd like to withdraw:</h2>
<p>Current Balance: <%= number_to_currency @current_account.balance %> </p>



<%= form_tag update_balance_path do %>
      <%= number_field_tag :balance, 0.01, min: 0.01, step: :any %>
      <%= hidden_field_tag :id, @current_account.id %>
      <%= hidden_field_tag :user_id, current_user.id %>
      <%= hidden_field_tag :transaction, "withdrawal" %>
      <%= submit_tag "Update Balance", class: "btn btn-success" %>
<% end %>